import TopBar from "@/components/chords/top-bar";
import { ScrollToTop } from "@/components/ui/scroll-to-top";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function ChordsLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
      <h2 className="text-4xl my-8 text-center font-bold tracking-tight lg:text-5xl text-primary">Библиотека аккордов</h2>
			<TopBar className="mb-8"></TopBar>
			{children}
			<ScrollToTop size={40} minHeight={600} scrollTo={10}>
			</ScrollToTop>
		</>
	);
}
