import TopBar from "@/components/chords/top-bar";
import { ScrollToTop } from "@/components/ui/scroll-to-top";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function ChordsLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			<TopBar className="mb-10"></TopBar>
			{children}
			<ScrollToTop minHeight={20} scrollTo={10} className="fixed rounded-full right-4 bottom-4 z-10 cursor-pointer w-12 h-12">
			</ScrollToTop>
		</>
	);
}
